# This file was auto-generated by cabal2nix. Please do NOT edit manually!

{ iCalendar-head ? ( import <nixpkgs>{}).myHaskellPackages.iCalendar,
  cabal, ansiTerminal }:

cabal.mkDerivation (self: {
  pname = "memento";
  version = "0.1.0.0";
  src = ./.;
  isLibrary = false;
  isExecutable = true;
  buildDepends = [ ansiTerminal iCalendar-head ];
  meta = {
    description = "Do Stuff. Now. Please.";
    license = self.stdenv.lib.licenses.mit;
    platforms = self.ghc.meta.platforms;
  };
})
