# This file was auto-generated by cabal2nix. Please do NOT edit manually!

{ cabal, ansiTerminal, dataDefault, httpClient, httpTypes
, iCalendar, optparseApplicative, text, time
}:

cabal.mkDerivation (self: {
  pname = "memento";
  version = "0.1.0.0";
  src = ./.;
  isLibrary = true;
  isExecutable = true;
  buildDepends = [
    ansiTerminal dataDefault httpClient httpTypes iCalendar
    optparseApplicative text time
  ];
  meta = {
    description = "Do Stuff. Now. Please.";
    license = self.stdenv.lib.licenses.mit;
    platforms = self.ghc.meta.platforms;
  };
})
